### ISSUE TITLE
Not able to compile with VS15 32bit

### ISSUE THREAD

**Issue by Lectem** [nvpro-samples/gl_vk_threaded_cadscene#1]
I tried to compile this sample with VS15 update1, but I encountered a few issues, using the default cmake configuration (32bit) and LunarG Vulkan SDK. There are in reality two issues :
# NSight and stdint.h

The stdint.h (https://github.com/nvpro-samples/shared_external/blob/master/NSight/stdint.h) header will be used instead of the compiler one, breaking cstdint.
# 32bit and LunarG SDK

If the NSight  stdint.h header is removed, another compilation error will be issued because of https://github.com/nvpro-samples/gl_vk_threaded_cadscene/blob/master/resources_vk.hpp#L367

`Error  C2572   'csfthreaded::ResourcesVK::allocMemAndBindObject' :member function already defined or declared gl_vk_threaded_cadscene e:\progs\pc\nvidiasamples\gl_vk_threaded_cadscene\resources_vk.hpp  367`

I think this is caused by VkImage being a typedef of uint64_t, and VkBuffer too when compiling for a 32bit platform. This issue doesn't appear on 64-bit versions because those are structs in 64bit versions

This is how those types are currently defined in the LunarG SDK:

``` c++
#if defined(__LP64__) || defined(_WIN64) || defined(__x86_64__) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *object;
#else
        #define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t object;
#endif
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkBuffer)
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkImage)
```

I am unsure if it is a problem of the SDK or this sample.

**Comment by chrisjhebert1973** [comment]
Hi Lectem
Are you building on a 32 bit OS? If not you should build for 64bit. The issue with stdint.h could be due to some newer definitions (such as int_fast8_t) from VS2015 that may be being masked out by the Nsight stdint.h.

If you are not using NSight you can temporarily work around this by removing _add_package_Nsight() from the cmake lists which will stop Nsights stdint.h from being added.

If you can try this and let me know if it helps I would appreciate it.

Many Thanks

Chris Hebert
Developer Technology
NVIDIA

**Comment by Lectem** [comment]
Hi, the problem with NSight is indeed solved by removing _add_package_Nsight() on 64-bit builds.
I think NSight should ship this header in a subdirectory and only add this in the include paths for platforms that require it, but it is not really the issue at hand here.

I am not using a 32bit OS, but I'd like to be able to run my program on such platforms. I would understand if making the code compatible is not an objective, but it might be worth having a note about it in the readme.

I suppose that the vulkan API design was not expecting VkImage and other handles types to be used to overload functions in c++, which is a bit sad.

**Comment by pixeljetstream** [comment]
Hi, pushed changes that remove that overload as it was not really needed in the sample.

**Comment by Lectem** [comment]
Hi, it now compiles fine, with the following fix https://github.com/nvpro-samples/shared_sources/pull/4 (and _add_package_Nsight() removed from the cmake lists)

**Comment by gigadude** [comment]
I just pulled this repo (c3c795d bbox init bug) and still hit this issue in 32bit mode. I switched to using:

cmake -G "Visual Studio 12 2013 Win64" ..

and it worked. Might want to add a `build.cmd` script to make this obvious...

**Comment by pixeljetstream** [comment]
closing, it is intentional that only 64-bit builds are supported
