### ISSUE TITLE
Build fails on VS2015, Vulkan SDK 1.0.39.1 and 1.0.37.0

### ISSUE THREAD

**Issue by ompadu** [nvpro-samples/gl_vk_threaded_cadscene#10]
`Error (active)		a value of type "VkIndexType" cannot be assigned to an entity of type "VkObjectEntryTypeNVX"	gl_vk_threaded_cadscene	(...)\gl_vk_threaded_cadscene\resources_vkgen.cpp	142`

**Comment by pixeljetstream** [comment]
fixed with newer Vulkan SDKs
