### ISSUE TITLE
Vulkan animation

### ISSUE THREAD

**Issue by pbc37** [nvpro-samples/gl_vk_threaded_cadscene#12]
When I select any Vulkan option the animation malfuntioncs. Here's an example:

![test](https://user-images.githubusercontent.com/17406294/68784649-2d3d8680-063d-11ea-84ba-def77b2ea92a.gif)

**Comment by pixeljetstream** [comment]
thanks for reporting, please use a workaround: disable animation prior changing renderer

**Comment by pbc37** [comment]
It keeps happening, sometimes it even disappears like this: 
![test2](https://user-images.githubusercontent.com/17406294/68865444-207b6a00-06f3-11ea-9d89-2928591e95ad.gif)

I think it's the objects go too far beyond the zfar of the camera and fast in the animation. When I switch back to OpenGL core it works but with Vulkan.
Here's more info:
- Project generated with CMake GUI 3.16.0 rc3
- Compiled with Visual Studio 2019
- Vulkan version 1.1.126.0
- shared external and shared source version: master
- This project version: master

**Comment by pixeljetstream** [comment]
please check latest commit, should fix it, thanks for reporting
