### ISSUE TITLE
the global scope has no "int_least8_t"	gl_vk_threaded_cadscene

### ISSUE THREAD

**Issue by andreluizbarbieri** [nvpro-samples/gl_vk_threaded_cadscene#2]
the global scope has no "int_least8_t"  gl_vk_threaded_cadscene
the global scope has no "int_least16_t" gl_vk_threaded_cadscene
the global scope has no "int_least32_t" gl_vk_threaded_cadscene
the global scope has no "int_least64_t" gl_vk_threaded_cadscene

**Comment by elect86** [comment]
I have the same errors in gl_commandlist_basic

**Comment by Delwin9999** [comment]
I have this problem too on Ubuntu 16.04 with GCC 6.0.1

It's complaining about the declarations in cstdint coming from the include of <string>.  There's a lot of mixing of C and C++ headers going on all over this project so it seems they may have tripped across each other.  I'm trying to untangle it and I'll submit a pull request when I figure it out.

**Comment by elect86** [comment]
I opened an issue [here](http://stackoverflow.com/questions/37008198/nv-pro-samples-compiling-failure-the-global-scope-has-no-int-least8-t) on stackoverflow, it is still unanswered although some lazy/superficial user tried to close it down

**Comment by llcdraco** [comment]
The same issue.

**Comment by chrisjhebert1973** [comment]
Can you try to build this without NSight support (remove addPackageNSight from the CMake).
Let me know if the issue persists.

**Comment by Delwin9999** [comment]
When I do that I get 

 error: no matching function for call to ‘push_back(const csfthreaded::Nulled<unsigned int>&)’

every time sc.fbos is called in renderthread_glcmd.cpp

**Comment by Delwin9999** [comment]
Fixed that by manually casting the sc.fbos->scene to a GLuint and it builds.  Still not working but that my be other issues.

**Comment by elect86** [comment]
I can confirm Chris suggestion worked for me.

Commenting out `_add_package_NSight()` inside `gl_commandlist_basic\CMakeList.txt` made it compiling!

Ps: I deleted all the projects and cloned them again before doing it
