### ISSUE TITLE
VK_API_VERSION no longer exists

### ISSUE THREAD

**Issue by computerquip** [nvpro-samples/gl_vk_threaded_cadscene#4]
It seems a breaking change was made in the loader, which was to remove VK_API_VERSION in favor of version specific macros like VK_MAKE_VERSION or VK_API_VERSION_1_0. vk_initlib.cpp thus fails to compile.

**Comment by TheBuzzSaw** [comment]
I ran into this too. Just setting it to `0` seems to be fine.

**Comment by pixeljetstream** [comment]
replaced it with VK_MAKE_VERSION(1, 0, 0)
